---
title: "Tidying Data"
output: github_document
date: "2024-09-24"
---

```{r, warning=FALSE,message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```
This document will show how to tidy data.

## Pivot longer with `pivot_longer`
```{r}
pulse_df <-
  read_sas("data/public_pulse_data.sas7bdat") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score",
    names_prefix = "bdi_score_"
  ) |>
  mutate(visit = replace(visit, visit == "bl", "00m")) |>
  relocate(id, visit)
```

One more example

```{r}
litters_df <- read_csv("data/FAS_litters.csv",
                       na = c("NA","","."),
                       show_col_types = FALSE) |>
  janitor::clean_names() |>
  pivot_longer(cols = gd0_weight:gd18_weight,
               names_to = "gd_time",
               values_to = "weight") |>
  mutate(gd_time = case_match(gd_time,
                              "gd0_weight" ~ 0,
                              "gd18_weight" ~ 18))
```

## Pivot wider with `pivot_wider`
Make up some analysis results
```{r}
analysis_df <-
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )
```

`pivot_wider` for human readability.
```{r}
analysis_df |>
  pivot_wider(names_from = "time",
              values_from = "mean") |>
  knitr::kable()
```

